=== azisaba/modchecker.azisaba.net/modinfo-schema.json
{
  "$ref": "#/definitions/ModInfo",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ModInfo": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "curseforge": {
            "type": "string"
          },
          "icon": {
            "type": "string"
          },
          "modrinth": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "note": {
            "type": "string"
          },
          "server": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "status": {
            "enum": [
              "allowed",
              "disallowed",
              "partially_allowed",
              "unknown"
            ],
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "version": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "status"
        ],
        "type": "object"
      },
      "type": "array"
    }
  }
}

=== azisaba/modchecker.azisaba.net/data/modinfo.json
[
  {
    "name": "Fabric API",
    "modrinth": "fabric-api",
    "curseforge": "fabric-api",
    "icon": "https://cdn.modrinth.com/data/P7dR8mSH/icon.png",
    "status": "allowed"
  },
  {
    "name": "Litematica",
    "modrinth": "litematica",
    "curseforge": "litematica",
    "icon": "https://cdn.modrinth.com/data/bEpr0Arc/25b5529d7a3b030ac136a6ce879d8ed2a1aa4a8d.png",
    "status": "partially_allowed",
    "note": "Easy Place Modeは処罰対象です。"
  },
  {
    "name": "Litematica Printer",
    "modrinth": "litematica-printer",
    "icon": "https://cdn.modrinth.com/data/3llatzyE/c71a268626b7a5413c68b47445327f5c948a2731.jpeg",
    "status": "disallowed"
  },
  {
    "name": "Inventory Tweaks",
    "curseforge": "inventory-tweaks",
    "icon": "https://media.forgecdn.net/avatars/thumbnails/9/423/256/256/635428742381702656.png",
    "status": "disallowed"
  },
  {
    "name": "Inventory Tweaks ReFoxed",
    "curseforge": "inventory-tweaks-refoxed",
    "icon": "https://media.forgecdn.net/avatars/thumbnails/951/92/256/256/638440158830430802.png",
    "status": "disallowed"
  },
  {
    "name": "U Team Core",
    "curseforge": "u-team-core",
    "icon": "https://media.forgecdn.net/avatars/thumbnails/108/684/256/256/636374315485450120.png",
    "status": "allowed"
  },
  {
    "name": "Music Player",
    "curseforge": "music-player",
    "icon": "https://media.forgecdn.net/avatars/thumbnails/154/699/256/256/636627791026604222.png",
    "status": "allowed"
  },
  {
    "name": "InterChatMod",
    "url": "https://github.com/AzisabaNetwork/InterChatMod",
    "status": "allowed"
  },
  {
    "name": "Optifine",
    "url": "https://optifine.net/downloads",
    "icon": "https://avatars.githubusercontent.com/u/69833574?s=200&v=4",
    "status": "allowed"
  },
  {
    "name": "Optifine",
    "url": "https://optifine.net/downloads",
    "icon": "https://avatars.githubusercontent.com/u/69833574?s=200&v=4",
    "status": "unknown",
    "server": ["LGW2"]
  },
  {
    "name": "Optifine",
    "url": "https://optifine.net/downloads",
    "icon": "https://avatars.githubusercontent.com/u/69833574?s=200&v=4",
    "status": "unknown",
    "server": ["Life"]
  },
  {
    "name": "JourneyMap",
    "curseforge": "journeymap",
    "modrinth": "journeymap",
    "icon": "https://media.forgecdn.net/avatars/thumbnails/9/144/256/256/635421614078544069.png",
    "status": "allowed"
  },
  {
    "name": "JourneyMap",
    "curseforge": "journeymap",
    "modrinth": "journeymap",
    "icon": "https://media.forgecdn.net/avatars/thumbnails/9/144/256/256/635421614078544069.png",
    "status": "disallowed",
    "server": ["LGW2"]
  },
  {
    "name": "Passive Shield",
    "curseforge": "passive-shield",
    "modrinth": "passive-shield",
    "icon": "https://cdn.modrinth.com/data/iQBrasyH/8a36d1dda1f0196fc1b63db829ad5b63badf0c71_96.webp",
    "status": "allowed"
  },
  {
    "name": "Passive Shield",
    "curseforge": "passive-shield",
    "modrinth": "passive-shield",
    "icon": "https://cdn.modrinth.com/data/iQBrasyH/8a36d1dda1f0196fc1b63db829ad5b63badf0c71_96.webp",
    "status": "disallowed",
    "server": ["LGW2"]
  }
]
